services:

  db:
    image: postgres:15
    container_name: nia_db
    restart: always
    environment:
      POSTGRES_USER: niauser
      POSTGRES_PASSWORD: niapass
      POSTGRES_DB: niadb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U niauser -d niadb"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nia_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://niauser:niapass@db:5432/niadb"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: nia_frontend
    depends_on:
      - backend
    ports:
      - "4000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules        # <- ADICIONE ESTA LINHA
      - /app/.next               # <- ADICIONE ESTA LINHA TAMBÃ‰M

volumes:
  pgdata: